/* Generated By:JavaCC: Do not edit this line. NormativeLanguageParserTreeConstants.java Version 4.1d1 */
package normativeLanguageParser;

public interface NormativeLanguageParserTreeConstants
{
  public int JJTNORM = 0;
  public int JJTDEONTICCONCEPT = 1;
  public int JJTENTITY = 2;
  public int JJTID = 3;
  public int JJTROLEUNIT = 4;
  public int JJTROLE = 5;
  public int JJTUNIT = 6;
  public int JJTAGENTROLEUNIT = 7;
  public int JJTAGENT = 8;
  public int JJTACTION = 9;
  public int JJTREQUEST = 10;
  public int JJTREGISTER = 11;
  public int JJTSERVE = 12;
  public int JJTSERVICE = 13;
  public int JJTMESSAGE = 14;
  public int JJTPROCESS = 15;
  public int JJTPROFILE = 16;
  public int JJTCONDITIONEXPRESSION = 17;
  public int JJTNOT = 18;
  public int JJTAND = 19;
  public int JJTOR = 20;
  public int JJTCONDITION = 21;
  public int JJTNORMID = 22;
  public int JJTVARIANT = 23;
  public int JJTATOMIC = 24;
  public int JJTIDVARIABLE = 25;
  public int JJTIDVALUE = 26;
  public int JJTVARIABLE = 27;
  public int JJTFORMULA = 28;
  public int JJTARGS = 29;
  public int JJTSERVICERESULT = 30;
  public int JJTCONTEXTTIME = 31;
  public int JJTVALUE = 32;
  public int JJTMESSAGEINFO = 33;
  public int JJTSENDER = 34;
  public int JJTRECEIVER = 35;
  public int JJTPERFORMATIVE = 36;
  public int JJTCONTENT = 37;
  public int JJTPROFILEDESCRIPTION = 38;
  public int JJTINPUT = 39;
  public int JJTOUTPUT = 40;
  public int JJTPRECONDITION = 41;
  public int JJTPOSTCONDITION = 42;
  public int JJTPARAMLIST = 43;
  public int JJTPARAMTYPE = 44;
  public int JJTTYPE = 45;
  public int JJTPARAMETERID = 46;
  public int JJTPROCESSDESCRIPTION = 47;
  public int JJTCONNECTS = 48;
  public int JJTPROCESSACTION = 49;
  public int JJTTASKID = 50;
  public int JJTJOIN = 51;
  public int JJTIFTHENELSE = 52;
  public int JJTIF = 53;
  public int JJTTHEN = 54;
  public int JJTELSE = 55;
  public int JJTWHILE = 56;
  public int JJTDO = 57;
  public int JJTTEMPORALSITUATION = 58;
  public int JJTBEFORE = 59;
  public int JJTAFTER = 60;
  public int JJTBETWEEN = 61;
  public int JJTSITUATION = 62;
  public int JJTDEADLINE = 63;
  public int JJTSANCTION = 64;
  public int JJTREWARD = 65;


  public String[] jjtNodeName = {
    "Norm",
    "DeonticConcept",
    "Entity",
    "ID",
    "RoleUnit",
    "Role",
    "Unit",
    "AgentRoleUnit",
    "Agent",
    "Action",
    "Request",
    "Register",
    "Serve",
    "Service",
    "Message",
    "Process",
    "Profile",
    "ConditionExpression",
    "Not",
    "And",
    "Or",
    "Condition",
    "NormID",
    "Variant",
    "Atomic",
    "IDVariable",
    "IDValue",
    "Variable",
    "Formula",
    "Args",
    "ServiceResult",
    "contextTime",
    "Value",
    "MessageInfo",
    "Sender",
    "Receiver",
    "Performative",
    "Content",
    "ProfileDescription",
    "Input",
    "Output",
    "Precondition",
    "Postcondition",
    "ParamList",
    "ParamType",
    "Type",
    "ParameterID",
    "ProcessDescription",
    "Connects",
    "ProcessAction",
    "TaskID",
    "Join",
    "IfThenElse",
    "If",
    "Then",
    "Else",
    "While",
    "Do",
    "TemporalSituation",
    "Before",
    "After",
    "Between",
    "Situation",
    "Deadline",
    "Sanction",
    "Reward",
  };
}
/* JavaCC - OriginalChecksum=41538832382d6c653c248e62f76a76ac (do not edit this line) */
