/* Generated By:JJTree&JavaCC: Do not edit this line. NormativeLanguageParserTokenManager.java */
package normativeLanguageParser;

/** Token Manager. */
public class NormativeLanguageParserTokenManager implements NormativeLanguageParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x10010000000L) != 0L)
         {
            jjmatchedKind = 49;
            return 5;
         }
         if ((active0 & 0x8480L) != 0L)
         {
            jjmatchedKind = 49;
            return 74;
         }
         if ((active0 & 0x1040000L) != 0L)
         {
            jjmatchedKind = 49;
            return 27;
         }
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 49;
            return 36;
         }
         if ((active0 & 0x385028d91b00L) != 0L)
         {
            jjmatchedKind = 49;
            return 48;
         }
         if ((active0 & 0x60000026000L) != 0L)
         {
            jjmatchedKind = 49;
            return 13;
         }
         if ((active0 & 0x8000000040L) != 0L)
         {
            jjmatchedKind = 49;
            return 24;
         }
         return -1;
      case 1:
         if ((active0 & 0x3f50297dff00L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 1;
            return 48;
         }
         if ((active0 & 0x10800040L) != 0L)
            return 48;
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 1;
            return 23;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 1;
            return 12;
         }
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 1;
            return 73;
         }
         return -1;
      case 2:
         if ((active0 & 0x20028000000L) != 0L)
            return 48;
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 2;
            return 11;
         }
         if ((active0 & 0x3dd0017dff80L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 2;
            return 48;
         }
         return -1;
      case 3:
         if ((active0 & 0x40000380000L) != 0L)
            return 48;
         if ((active0 & 0x39d00147ff80L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 3;
            return 48;
         }
         return -1;
      case 4:
         if ((active0 & 0x29500107fb80L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 4;
            return 48;
         }
         if ((active0 & 0x108000400400L) != 0L)
            return 48;
         return -1;
      case 5:
         if ((active0 & 0x94000008100L) != 0L)
            return 48;
         if ((active0 & 0x201001077a80L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 5;
            return 48;
         }
         return -1;
      case 6:
         if ((active0 & 0x200001007200L) != 0L)
            return 48;
         if ((active0 & 0x1000070880L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 6;
            return 48;
         }
         return -1;
      case 7:
         if ((active0 & 0x1000050880L) != 0L)
            return 48;
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 7;
            return 48;
         }
         return -1;
      case 8:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 8;
            return 48;
         }
         return -1;
      case 9:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 9;
            return 48;
         }
         return -1;
      case 10:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 10;
            return 48;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 30);
      case 41:
         return jjStopAtPos(0, 31);
      case 44:
         return jjStopAtPos(0, 37);
      case 45:
         return jjStopAtPos(0, 26);
      case 58:
         return jjStopAtPos(0, 25);
      case 91:
         return jjStopAtPos(0, 32);
      case 93:
         return jjStopAtPos(0, 33);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x100008000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x280000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1040000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x8000000040L);
      case 74:
      case 106:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x10010000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x60000026000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa1_0(0x1000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x4000010b00L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x8480L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x100000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      default :
         return jjMoveNfa_0(6, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x284000039f00L);
      case 70:
      case 102:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(1, 6, 48);
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x500000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x8008000000L);
      case 79:
      case 111:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(1, 23, 48);
         return jjMoveStringLiteralDfa2_0(active0, 0x400210c0000L);
      case 82:
      case 114:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(1, 28, 48);
         return jjMoveStringLiteralDfa2_0(active0, 0x20000006000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x11000000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      case 68:
      case 100:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(2, 27, 48);
         break;
      case 69:
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 41, 48);
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x480000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x1048080L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x6000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0x200L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x20400L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x44000201000L);
      case 84:
      case 116:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(2, 29, 48);
         return jjMoveStringLiteralDfa3_0(active0, 0x310000000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x100L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x2080L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 69:
      case 101:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 21, 48);
         return jjMoveStringLiteralDfa4_0(active0, 0x100000010000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0x24000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      case 78:
      case 110:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 48);
         else if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 48);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000040000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      case 84:
      case 116:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 42, 48);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0xc000000200L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      case 69:
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 48);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(4, 22, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0x20000104a200L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x14000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000L);
      case 82:
      case 114:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 44, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000100L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 84:
      case 116:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 39, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000080L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000L);
      case 68:
      case 100:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(5, 8, 48);
         break;
      case 69:
      case 101:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 43, 48);
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000080L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000L);
      case 82:
      case 114:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 48);
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x2200L);
      case 84:
      case 116:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 48);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 40, 48);
         return jjMoveStringLiteralDfa6_0(active0, 0x800L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(6, 12, 48);
         else if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(6, 14, 48);
         return jjMoveStringLiteralDfa7_0(active0, 0x10800L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000L);
      case 78:
      case 110:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 45, 48);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x80L);
      case 83:
      case 115:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 13, 48);
         break;
      case 84:
      case 116:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(6, 9, 48);
         else if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(6, 24, 48);
         return jjMoveStringLiteralDfa7_0(active0, 0x1000040000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000L);
      case 78:
      case 110:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(7, 7, 48);
         break;
      case 82:
      case 114:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(7, 11, 48);
         else if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(7, 16, 48);
         break;
      case 83:
      case 115:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(7, 18, 48);
         break;
      case 89:
      case 121:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 36, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 84:
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 86:
      case 118:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(11, 17, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 80;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 73:
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 6:
                  if ((0x7000000000000000L & l) != 0L)
                  {
                     if (kind > 34)
                        kind = 34;
                  }
                  else if (curChar == 39)
                     jjCheckNAddTwoStates(42, 43);
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(39, 40);
                  else if (curChar == 63)
                     jjstateSet[jjnewStateCnt++] = 45;
                  if (curChar == 62)
                     jjCheckNAdd(16);
                  else if (curChar == 60)
                     jjCheckNAdd(16);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 15:
                  if ((0x7000000000000000L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 16:
                  if (curChar == 61 && kind > 34)
                     kind = 34;
                  break;
               case 17:
                  if (curChar == 60)
                     jjCheckNAdd(16);
                  break;
               case 18:
                  if (curChar == 62)
                     jjCheckNAdd(16);
                  break;
               case 38:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(39, 40);
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(39, 40);
                  break;
               case 40:
                  if (curChar == 34 && kind > 47)
                     kind = 47;
                  break;
               case 41:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(42, 43);
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(42, 43);
                  break;
               case 43:
                  if (curChar == 39 && kind > 47)
                     kind = 47;
                  break;
               case 44:
                  if (curChar == 63)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjstateSet[jjnewStateCnt++] = 46;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 73:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 12:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 74:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  else if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 24:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 13:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 6:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(0, 1);
                  else if ((0x4000000040L & l) != 0L)
                     jjAddStates(2, 4);
                  else if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  else if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  else if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  else if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  else if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 11:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 27:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 36:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 5:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 23:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(48);
                  }
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 0:
                  if ((0x1000000010L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 1:
               case 7:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAdd(0);
                  break;
               case 2:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 8:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 14:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 19:
                  if ((0x4000000040000L & l) != 0L && kind > 46)
                     kind = 46;
                  break;
               case 20:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAdd(19);
                  break;
               case 21:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 25:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if ((0x200000002L & l) != 0L)
                     jjCheckNAdd(19);
                  break;
               case 28:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if ((0x2000000020L & l) != 0L && kind > 46)
                     kind = 46;
                  break;
               case 30:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 37:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 39:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjAddStates(5, 6);
                  break;
               case 42:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjAddStates(7, 8);
                  break;
               case 45:
               case 46:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjCheckNAdd(46);
                  break;
               case 47:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 48:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(48);
                  break;
               case 49:
                  if ((0x4000000040L & l) != 0L)
                     jjAddStates(2, 4);
                  break;
               case 50:
                  if ((0x400000004000L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 51:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if ((0x1000000010L & l) != 0L && kind > 35)
                     kind = 35;
                  break;
               case 59:
               case 68:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAdd(58);
                  break;
               case 60:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if ((0x10000000100000L & l) != 0L && kind > 46)
                     kind = 46;
                  break;
               case 64:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(0, 1);
                  break;
               case 69:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 75:
                  if ((0x8000000080L & l) != 0L && kind > 46)
                     kind = 46;
                  break;
               case 76:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 80 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   74, 79, 57, 62, 66, 39, 40, 42, 43, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, "\72", 
"\55", null, null, null, "\50", "\51", "\133", "\135", null, null, null, "\54", null, 
null, null, null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x3ffffffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[80];
private final int[] jjstateSet = new int[160];
protected char curChar;
/** Constructor. */
public NormativeLanguageParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public NormativeLanguageParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 80; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
