#!/bin/bash

ruta="qpidc-0.5/src/qpid/broker"

cd $ruta

cat Daemon.cpp | head -89 > kk.cpp

echo " ssize_t basura = write(pipeFds[1], &port, sizeof(uint16_t));

            std::string pipeFailureMessage = e.what();
            basura = write ( pipeFds[1], 
                    pipeFailureMessage.c_str(), 
                    strlen(pipeFailureMessage.c_str())
                  );" >> kk.cpp
cat Daemon.cpp | tail -116 >> kk.cpp
mv kk.cpp Daemon.cpp
cd ../sys/posix
cat LockFile.cpp | head -58 > kk.cpp
echo "int basura;
      basura  =::lockf(f, F_ULOCK, 0); // Suppress warnings about ignoring return value." >> kk.cpp
cat LockFile.cpp | tail -30 >> kk.cpp
mv kk.cpp LockFile.cpp
cd ../../agent
cat ManagementAgentImpl.cpp | head -538 > kk.cpp
echo " ssize_t basura; 
       basura = write(writeFd, \"X\", 1);" >> kk.cpp
cat ManagementAgentImpl.cpp | tail -373 >> kk.cpp
mv kk.cpp ManagementAgentImpl.cpp

