/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on Apr 11, 2010, 11:59:54 PM
 */

package MMS_Example;


import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Hashtable;

import org.apache.log4j.xml.DOMConfigurator;

import es.upv.dsic.gti_ia.core.AgentID;
import es.upv.dsic.gti_ia.core.AgentsConnection;
/**
 *
 * @author joabelfa
 */
public class GUI extends javax.swing.JFrame {

  private static final long serialVersionUID = 1L;
	Hashtable<String, Object> payeehashtable, providerhashtable,
			customerhashtable;
	Hashtable<String, Object> payeeserviceshashtable,
			providerserviceshashtable, customerserviceshashtable;
	private MMS agentMMS = null;
	private Agent agentOne = null;
	private Agent agentTwo = null;


    /** Creates new form GUI */
    public GUI() {
    	initComponents();
		/**
		 * Setting the Logger
		 */
		DOMConfigurator.configure("configuration/loggin.xml");
		// Logger logger = Logger.getLogger(Run.class);

		/**
		 * Connecting to Qpid Broker
		 */
		AgentsConnection.SecureConnect();
		AgentsConnection.connect();

		try {
			/**
			 * Instantiating a MMS agent
			 */
		agentMMS = new MMS(new AgentID("MMS"));

		agentMMS.start();

		} catch (Exception e) {
			System.out.println("Error:" + e.getMessage());
		}

		this.loadFile();
	}

	public void loadFile() {
		FileReader fr = null;
		String sCadena = null, buffer = "";

		try {
			fr = new FileReader("./certificates/broker.acl");
			BufferedReader bf = new BufferedReader(fr);
			try {
				while ((sCadena = bf.readLine()) != null) {
					buffer = buffer.concat(sCadena);
					buffer = buffer.concat("\n");
				}
				this.jTextArea2.setText(buffer);
			} catch (IOException ex) {
				// Logger.getLogger(ThomasGUI.class.getName()).log(Level.SEVERE,
				// null, ex);
				// logger.error(ex.getMessage());
			}
		} catch (FileNotFoundException ex) {
			// Logger.getLogger(ThomasGUI.class.getName()).log(Level.SEVERE,
			// null, ex);
			// logger.error(ex.getMessage());
		} finally {
			try {
				fr.close();
			} catch (IOException ex) {
				// Logger.getLogger(ThomasGUI.class.getName()).log(Level.SEVERE,
				// null, ex);
				// logger.error(ex.getMessage());
			}
		}

		

	}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        PayeePanel1 = new javax.swing.JPanel();
        jToolBarPayee1 = new javax.swing.JToolBar();
        logPanel1 = new javax.swing.JPanel();
        clearLogButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        reloadPayeeButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        StartAgent2 = new javax.swing.JButton();
        StopAgent2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        PayeePanel = new javax.swing.JPanel();
        jToolBarPayee = new javax.swing.JToolBar();
        logPanel = new javax.swing.JPanel();
        clearLogButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        reloadPayeeButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        StartAgent1 = new javax.swing.JButton();
        StopAgent1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        travelAgencyPanel = new javax.swing.JPanel();
        clientStartButton = new javax.swing.JButton();
        pensadorLabel = new javax.swing.JLabel();
        upvLabel = new javax.swing.JLabel();
        scenarioStartButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        travelAgencyPanel1 = new javax.swing.JPanel();
        clientStartButton1 = new javax.swing.JButton();
        pensadorLabel1 = new javax.swing.JLabel();
        upvLabel1 = new javax.swing.JLabel();
        scenarioStartButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        iconLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        PayeePanel3 = new javax.swing.JPanel();
        logPanel3 = new javax.swing.JPanel();
        clearLogButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        reloadPayeeButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        StartAgent4 = new javax.swing.JButton();
        StopAgent4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PayeePanel2 = new javax.swing.JPanel();
        logPanel2 = new javax.swing.JPanel();
        clearLogButton2 = new javax.swing.JButton();
        reloadPayeeButton2 = new javax.swing.JButton();
        StartAgent5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        StopAgent5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        PayeePanel1.setPreferredSize(new java.awt.Dimension(1320, 766));

        jToolBarPayee1.setRollover(true);

        clearLogButton1.setText("Clear Log");
        clearLogButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logPanel1Layout = new javax.swing.GroupLayout(logPanel1);
        logPanel1.setLayout(logPanel1Layout);
        logPanel1Layout.setHorizontalGroup(
            logPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanel1Layout.createSequentialGroup()
                .addContainerGap(1190, Short.MAX_VALUE)
                .addComponent(clearLogButton1)
                .addGap(57, 57, 57))
        );
        logPanel1Layout.setVerticalGroup(
            logPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(clearLogButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 36));
        jLabel4.setText("Agent Information");

        reloadPayeeButton1.setFocusable(false);
        reloadPayeeButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reloadPayeeButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reloadPayeeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadPayeeButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Send");

        StartAgent2.setText("Start");
        StartAgent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartAgent2ActionPerformed(evt);
            }
        });

        StopAgent2.setText("Stop");
        StopAgent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopAgent2ActionPerformed(evt);
            }
        });

        jButton5.setText("Send");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Send with other entity");

        javax.swing.GroupLayout PayeePanel1Layout = new javax.swing.GroupLayout(PayeePanel1);
        PayeePanel1.setLayout(PayeePanel1Layout);
        PayeePanel1Layout.setHorizontalGroup(
            PayeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayeePanel1Layout.createSequentialGroup()
                .addGroup(PayeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PayeePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PayeePanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PayeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PayeePanel1Layout.createSequentialGroup()
                                .addComponent(StartAgent2)
                                .addGap(1475, 1475, 1475)
                                .addComponent(reloadPayeeButton1))
                            .addComponent(jLabel4)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StopAgent2)
                            .addGroup(PayeePanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addComponent(jToolBarPayee1, javax.swing.GroupLayout.DEFAULT_SIZE, 1565, Short.MAX_VALUE))
                .addContainerGap())
        );
        PayeePanel1Layout.setVerticalGroup(
            PayeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayeePanel1Layout.createSequentialGroup()
                .addComponent(jToolBarPayee1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PayeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PayeePanel1Layout.createSequentialGroup()
                        .addComponent(reloadPayeeButton1)
                        .addGap(27, 27, 27))
                    .addGroup(PayeePanel1Layout.createSequentialGroup()
                        .addComponent(StartAgent2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(StopAgent2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(16, 16, 16)
                .addGroup(PayeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(323, 323, 323)
                .addComponent(logPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Agent 2", PayeePanel1);

        PayeePanel.setPreferredSize(new java.awt.Dimension(1320, 766));

        jToolBarPayee.setRollover(true);

        clearLogButton.setText("Clear Log");
        clearLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanelLayout.createSequentialGroup()
                .addContainerGap(1190, Short.MAX_VALUE)
                .addComponent(clearLogButton)
                .addGap(57, 57, 57))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(clearLogButton)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 36));
        jLabel3.setText("Agent Information");

        reloadPayeeButton.setFocusable(false);
        reloadPayeeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reloadPayeeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reloadPayeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadPayeeButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Send");

        StartAgent1.setText("Start");
        StartAgent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartAgent1ActionPerformed(evt);
            }
        });

        StopAgent1.setText("Stop");
        StopAgent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopAgent1ActionPerformed(evt);
            }
        });

        jButton4.setText("Send");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Send with oher entity");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PayeePanelLayout = new javax.swing.GroupLayout(PayeePanel);
        PayeePanel.setLayout(PayeePanelLayout);
        PayeePanelLayout.setHorizontalGroup(
            PayeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayeePanelLayout.createSequentialGroup()
                .addGroup(PayeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PayeePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PayeePanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PayeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PayeePanelLayout.createSequentialGroup()
                                .addComponent(StartAgent1)
                                .addGap(1425, 1425, 1425)
                                .addComponent(reloadPayeeButton))
                            .addComponent(jLabel3)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StopAgent1)
                            .addGroup(PayeePanelLayout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)))
                    .addComponent(jToolBarPayee, javax.swing.GroupLayout.DEFAULT_SIZE, 1515, Short.MAX_VALUE))
                .addContainerGap())
        );
        PayeePanelLayout.setVerticalGroup(
            PayeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayeePanelLayout.createSequentialGroup()
                .addComponent(jToolBarPayee, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(PayeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PayeePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reloadPayeeButton)
                        .addGap(60, 60, 60))
                    .addGroup(PayeePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StartAgent1)
                        .addGap(6, 6, 6)
                        .addComponent(StopAgent1)
                        .addGap(6, 6, 6)))
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PayeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(327, 327, 327)
                .addComponent(logPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Agent 1", PayeePanel);

        clientStartButton.setText("writeACLFile");
        clientStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientStartButtonActionPerformed(evt);
            }
        });

        scenarioStartButton.setText("loadACLFile");
        scenarioStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scenarioStartButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel2.setText("Content of Broker.acl");

        jButton3.setText("Clear Broker.acl");

        javax.swing.GroupLayout travelAgencyPanelLayout = new javax.swing.GroupLayout(travelAgencyPanel);
        travelAgencyPanel.setLayout(travelAgencyPanelLayout);
        travelAgencyPanelLayout.setHorizontalGroup(
            travelAgencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(travelAgencyPanelLayout.createSequentialGroup()
                .addGroup(travelAgencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(travelAgencyPanelLayout.createSequentialGroup()
                        .addGap(554, 554, 554)
                        .addComponent(jLabel1))
                    .addGroup(travelAgencyPanelLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(upvLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(pensadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300)
                        .addComponent(iconLabel))
                    .addGroup(travelAgencyPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(travelAgencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(travelAgencyPanelLayout.createSequentialGroup()
                                .addGroup(travelAgencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(clientStartButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(scenarioStartButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(travelAgencyPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        travelAgencyPanelLayout.setVerticalGroup(
            travelAgencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(travelAgencyPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(scenarioStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(travelAgencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(travelAgencyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clientStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(travelAgencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addGroup(travelAgencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(iconLabel)
                    .addComponent(pensadorLabel)
                    .addComponent(upvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jTabbedPane5.addTab("MMS Control", travelAgencyPanel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientStartButton1.setText("writeACLFile");
        clientStartButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientStartButton1ActionPerformed(evt);
            }
        });

        scenarioStartButton1.setText("loadACLFile");
        scenarioStartButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scenarioStartButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jLabel12.setText("Content of Broker.acl");

        jButton10.setText("Clear Broker.acl");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout travelAgencyPanel1Layout = new javax.swing.GroupLayout(travelAgencyPanel1);
        travelAgencyPanel1.setLayout(travelAgencyPanel1Layout);
        travelAgencyPanel1Layout.setHorizontalGroup(
            travelAgencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(travelAgencyPanel1Layout.createSequentialGroup()
                .addGroup(travelAgencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(travelAgencyPanel1Layout.createSequentialGroup()
                        .addGap(554, 554, 554)
                        .addComponent(jLabel11))
                    .addGroup(travelAgencyPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(upvLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(pensadorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300)
                        .addComponent(iconLabel1))
                    .addGroup(travelAgencyPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(travelAgencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(travelAgencyPanel1Layout.createSequentialGroup()
                                .addGroup(travelAgencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(clientStartButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(scenarioStartButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(travelAgencyPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton10))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        travelAgencyPanel1Layout.setVerticalGroup(
            travelAgencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(travelAgencyPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(scenarioStartButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(travelAgencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(travelAgencyPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clientStartButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(travelAgencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addGroup(travelAgencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(iconLabel1)
                    .addComponent(pensadorLabel1)
                    .addComponent(upvLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("MMS Control", travelAgencyPanel1);

        PayeePanel3.setPreferredSize(new java.awt.Dimension(1320, 766));

        clearLogButton3.setText("Clear Log");
        clearLogButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logPanel3Layout = new javax.swing.GroupLayout(logPanel3);
        logPanel3.setLayout(logPanel3Layout);
        logPanel3Layout.setHorizontalGroup(
            logPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanel3Layout.createSequentialGroup()
                .addContainerGap(1190, Short.MAX_VALUE)
                .addComponent(clearLogButton3)
                .addGap(57, 57, 57))
        );
        logPanel3Layout.setVerticalGroup(
            logPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(clearLogButton3)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 36));
        jLabel9.setText("Agent Information");

        reloadPayeeButton3.setFocusable(false);
        reloadPayeeButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reloadPayeeButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reloadPayeeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadPayeeButton3ActionPerformed(evt);
            }
        });

        jButton8.setText("Send");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        StartAgent4.setText("Start");
        StartAgent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartAgent4ActionPerformed(evt);
            }
        });

        StopAgent4.setText("Stop");
        StopAgent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopAgent4ActionPerformed(evt);
            }
        });

        jButton9.setText("Send");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel10.setText("Send with oher entity");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel13.setText("I'm: ");

        jLabel14.setText("Agent");

        javax.swing.GroupLayout PayeePanel3Layout = new javax.swing.GroupLayout(PayeePanel3);
        PayeePanel3.setLayout(PayeePanel3Layout);
        PayeePanel3Layout.setHorizontalGroup(
            PayeePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayeePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PayeePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PayeePanel3Layout.createSequentialGroup()
                        .addGroup(PayeePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PayeePanel3Layout.createSequentialGroup()
                                .addComponent(StartAgent4)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addGap(127, 127, 127))
                            .addComponent(jLabel9)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StopAgent4)
                            .addGroup(PayeePanel3Layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addGap(1122, 1122, 1122)
                        .addComponent(reloadPayeeButton3)))
                .addContainerGap())
        );
        PayeePanel3Layout.setVerticalGroup(
            PayeePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayeePanel3Layout.createSequentialGroup()
                .addGroup(PayeePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PayeePanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reloadPayeeButton3)
                        .addGap(480, 480, 480))
                    .addGroup(PayeePanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PayeePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PayeePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addGroup(PayeePanel3Layout.createSequentialGroup()
                                .addComponent(StartAgent4)
                                .addGap(6, 6, 6)
                                .addComponent(StopAgent4)))
                        .addGap(6, 6, 6)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PayeePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(logPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agent 1", PayeePanel3);

        PayeePanel2.setPreferredSize(new java.awt.Dimension(1320, 766));

        clearLogButton2.setText("Clear Log");
        clearLogButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logPanel2Layout = new javax.swing.GroupLayout(logPanel2);
        logPanel2.setLayout(logPanel2Layout);
        logPanel2Layout.setHorizontalGroup(
            logPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanel2Layout.createSequentialGroup()
                .addContainerGap(1190, Short.MAX_VALUE)
                .addComponent(clearLogButton2)
                .addGap(57, 57, 57))
        );
        logPanel2Layout.setVerticalGroup(
            logPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(clearLogButton2)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        reloadPayeeButton2.setFocusable(false);
        reloadPayeeButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reloadPayeeButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reloadPayeeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadPayeeButton2ActionPerformed(evt);
            }
        });

        StartAgent5.setText("Start");
        StartAgent5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartAgent5ActionPerformed(evt);
            }
        });

        jLabel15.setText("I'm: ");

        jLabel16.setText("Agent");

        StopAgent5.setText("Stop");
        StopAgent5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopAgent5ActionPerformed(evt);
            }
        });

        jButton11.setText("Send");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel17.setText("Send with oher entity");

        jButton12.setText("Send");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 36));
        jLabel18.setText("Agent Information");

        javax.swing.GroupLayout PayeePanel2Layout = new javax.swing.GroupLayout(PayeePanel2);
        PayeePanel2.setLayout(PayeePanel2Layout);
        PayeePanel2Layout.setHorizontalGroup(
            PayeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayeePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PayeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PayeePanel2Layout.createSequentialGroup()
                        .addGroup(PayeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PayeePanel2Layout.createSequentialGroup()
                                .addComponent(StartAgent5)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addGap(127, 127, 127))
                            .addComponent(jLabel18)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StopAgent5)
                            .addGroup(PayeePanel2Layout.createSequentialGroup()
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))
                        .addGap(1213, 1213, 1213)
                        .addComponent(reloadPayeeButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PayeePanel2Layout.setVerticalGroup(
            PayeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayeePanel2Layout.createSequentialGroup()
                .addGroup(PayeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PayeePanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reloadPayeeButton2)
                        .addGap(480, 480, 480))
                    .addGroup(PayeePanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PayeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PayeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addGroup(PayeePanel2Layout.createSequentialGroup()
                                .addComponent(StartAgent5)
                                .addGap(6, 6, 6)
                                .addComponent(StopAgent5)))
                        .addGap(6, 6, 6)
                        .addComponent(jButton11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PayeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton12)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(logPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agent 2", PayeePanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientStartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientStartButtonActionPerformed

    private void scenarioStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scenarioStartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scenarioStartButtonActionPerformed

    private void clearLogButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLogButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearLogButton1ActionPerformed

    private void reloadPayeeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadPayeeButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reloadPayeeButton1ActionPerformed

    private void StartAgent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartAgent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartAgent2ActionPerformed

    private void StopAgent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopAgent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StopAgent2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void clearLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLogButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearLogButtonActionPerformed

    private void reloadPayeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadPayeeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reloadPayeeButtonActionPerformed

    private void StartAgent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartAgent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartAgent1ActionPerformed

    private void StopAgent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopAgent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StopAgent1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void clearLogButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLogButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearLogButton2ActionPerformed

    private void reloadPayeeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadPayeeButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reloadPayeeButton2ActionPerformed

    private void clearLogButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLogButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearLogButton3ActionPerformed

    private void reloadPayeeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadPayeeButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reloadPayeeButton3ActionPerformed

    private void StartAgent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartAgent4ActionPerformed
        		try {
			agentOne = new Agent(
					new AgentID("luis"),
					"/home/joabelfa/wokspace/c++/certificates/certificates/keystore.jks",
					"key123", "SunX509");
		} catch (Exception e) {

			e.printStackTrace();
		}
		this.agentOne.start();
		
		this.jLabel14.setText(this.agentOne.getAid().name);
    }//GEN-LAST:event_StartAgent4ActionPerformed

    private void StopAgent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopAgent4ActionPerformed
        	this.agentOne.exit();
		this.agentOne = null;
    }//GEN-LAST:event_StopAgent4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        agentOne.send(this.jTextField5.getText(),"guest");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void clientStartButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientStartButton1ActionPerformed
       	this.agentMMS.writeAclFile(this.jTextField6.getText());
		this.jTextField6.setText("");
		this.loadFile();
    }//GEN-LAST:event_clientStartButton1ActionPerformed

    private void scenarioStartButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scenarioStartButton1ActionPerformed
        this.agentMMS.readACLFile();
    }//GEN-LAST:event_scenarioStartButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       this.agentMMS.clearACLFile();
		this.loadFile();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        agentOne.send(this.agentOne.getAid().name,"guest");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void StartAgent5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartAgent5ActionPerformed
       		try {

			/**
			 * Instantiating a sender agent
			 */
			agentTwo = new Agent(
					new AgentID("guest"),
					"/home/joabelfa/wokspace/c++/certificates/clientV2/keystore.jks",
					"key123", "SunX509");

			agentTwo.start();
			this.jLabel16.setText(this.agentTwo.getAid().name);
		} catch (Exception e) {
			// logger.error("Error  " + e.getMessage());
		}
    }//GEN-LAST:event_StartAgent5ActionPerformed

    private void StopAgent5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopAgent5ActionPerformed
       		this.agentTwo.exit();
		this.agentTwo = null;
    }//GEN-LAST:event_StopAgent5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       agentTwo.send(this.agentTwo.getAid().name,"luis");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     agentTwo.send(this.jTextField7.getText(),"luis");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PayeePanel;
    private javax.swing.JPanel PayeePanel1;
    private javax.swing.JPanel PayeePanel2;
    private javax.swing.JPanel PayeePanel3;
    private javax.swing.JButton StartAgent1;
    private javax.swing.JButton StartAgent2;
    private javax.swing.JButton StartAgent4;
    private javax.swing.JButton StartAgent5;
    private javax.swing.JButton StopAgent1;
    private javax.swing.JButton StopAgent2;
    private javax.swing.JButton StopAgent4;
    private javax.swing.JButton StopAgent5;
    private javax.swing.JButton clearLogButton;
    private javax.swing.JButton clearLogButton1;
    private javax.swing.JButton clearLogButton2;
    private javax.swing.JButton clearLogButton3;
    private javax.swing.JButton clientStartButton;
    private javax.swing.JButton clientStartButton1;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel iconLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToolBar jToolBarPayee;
    private javax.swing.JToolBar jToolBarPayee1;
    private javax.swing.JPanel logPanel;
    private javax.swing.JPanel logPanel1;
    private javax.swing.JPanel logPanel2;
    private javax.swing.JPanel logPanel3;
    private javax.swing.JLabel pensadorLabel;
    private javax.swing.JLabel pensadorLabel1;
    private javax.swing.JButton reloadPayeeButton;
    private javax.swing.JButton reloadPayeeButton1;
    private javax.swing.JButton reloadPayeeButton2;
    private javax.swing.JButton reloadPayeeButton3;
    private javax.swing.JButton scenarioStartButton;
    private javax.swing.JButton scenarioStartButton1;
    private javax.swing.JPanel travelAgencyPanel;
    private javax.swing.JPanel travelAgencyPanel1;
    private javax.swing.JLabel upvLabel;
    private javax.swing.JLabel upvLabel1;
    // End of variables declaration//GEN-END:variables

}
