/* Generated By:JavaCC: Do not edit this line. NormsTokenManager.java */
package es.upv.dsic.gti_ia.norms;
import es.upv.dsic.gti_ia.organization.exception.THOMASMessages.MessageID;
import es.upv.dsic.gti_ia.organization.exception.InvalidParametersException;
import es.upv.dsic.gti_ia.organization.exception.THOMASMessages;
import es.upv.dsic.gti_ia.organization.exception.NotCreatorInParentUnitException;
import es.upv.dsic.gti_ia.organization.exception.THOMASException;

/** Token Manager. */
public class NormsTokenManager implements NormsConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x50000000000000L) != 0L || (active1 & 0x1800L) != 0L)
         {
            jjmatchedKind = 5;
            return 26;
         }
         if ((active0 & 0x10020000000L) != 0L)
         {
            jjmatchedKind = 57;
            return 8;
         }
         if ((active0 & 0x2000000a800000L) != 0L)
         {
            jjmatchedKind = 57;
            return 15;
         }
         if ((active0 & 0xffeffd5600200L) != 0L || (active1 & 0xc7e0L) != 0L)
         {
            jjmatchedKind = 57;
            return 32;
         }
         if ((active1 & 0x2000L) != 0L)
         {
            jjmatchedKind = 5;
            return 32;
         }
         return -1;
      case 1:
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 1;
            return 25;
         }
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 1;
            return 14;
         }
         if ((active0 & 0x1fffffffe00200L) != 0L || (active1 & 0xffe0L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 1;
            return 32;
         }
         return -1;
      case 2:
         if ((active0 & 0x1fffffff800000L) != 0L || (active1 & 0xffe0L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 2;
            return 32;
         }
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 2;
            return 13;
         }
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 2;
            return 24;
         }
         if ((active0 & 0x600200L) != 0L)
            return 32;
         return -1;
      case 3:
         if ((active0 & 0x1fffffff800000L) != 0L || (active1 & 0xffe0L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 3;
            return 32;
         }
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 3;
            return 23;
         }
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 3;
            return 12;
         }
         return -1;
      case 4:
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 4;
            return 22;
         }
         if ((active0 & 0x3fffffff800000L) != 0L || (active1 & 0x9fe0L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 4;
            return 32;
         }
         return -1;
      case 5:
         if ((active0 & 0x3ddbffff800000L) != 0L || (active1 & 0x9fe0L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 5;
            return 32;
         }
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 5;
            return 21;
         }
         if ((active0 & 0x2240000000000L) != 0L)
            return 32;
         return -1;
      case 6:
         if ((active0 & 0x35d3ffff800000L) != 0L || (active1 & 0x97a0L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 6;
            return 32;
         }
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 6;
            return 20;
         }
         if ((active0 & 0x8080000000000L) != 0L)
            return 32;
         return -1;
      case 7:
         if ((active0 & 0x35d3ff7f800000L) != 0L || (active1 & 0x8780L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 7;
            return 32;
         }
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 7;
            return 19;
         }
         if ((active0 & 0x80000000L) != 0L)
            return 32;
         return -1;
      case 8:
         if ((active0 & 0x65c1ff7f800000L) != 0L || (active1 & 0x8180L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 8;
            return 32;
         }
         if ((active0 & 0x10120000000000L) != 0L)
            return 32;
         return -1;
      case 9:
         if ((active0 & 0x61c1277f800000L) != 0L || (active1 & 0x180L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 57;
               jjmatchedPos = 9;
            }
            return 32;
         }
         if ((active0 & 0x400d800000000L) != 0L)
            return 32;
         return -1;
      case 10:
         if ((active0 & 0x60c0377f800000L) != 0L || (active1 & 0x100L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 10;
            return 32;
         }
         if ((active0 & 0x1010000000000L) != 0L)
            return 32;
         return -1;
      case 11:
         if ((active0 & 0x60c03755000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 11;
            return 32;
         }
         if ((active0 & 0x2a800000L) != 0L)
            return 32;
         return -1;
      case 12:
         if ((active0 & 0x60403555000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 12;
            return 32;
         }
         if ((active0 & 0x800200000000L) != 0L)
            return 32;
         return -1;
      case 13:
         if ((active0 & 0x60403500000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 13;
            return 32;
         }
         if ((active0 & 0x55000000L) != 0L)
            return 32;
         return -1;
      case 14:
         if ((active0 & 0x40402400000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 14;
            return 32;
         }
         if ((active0 & 0x20001100000000L) != 0L)
            return 32;
         return -1;
      case 15:
         if ((active0 & 0x40002400000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 15;
            return 32;
         }
         if ((active0 & 0x400000000000L) != 0L)
            return 32;
         return -1;
      case 16:
         if ((active0 & 0x40000400000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 16;
            return 32;
         }
         if ((active0 & 0x2000000000L) != 0L)
            return 32;
         return -1;
      case 17:
         if ((active0 & 0x40000400000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 17;
            return 32;
         }
         return -1;
      case 18:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 18;
            return 32;
         }
         if ((active0 & 0x40000000000000L) != 0L)
            return 32;
         return -1;
      case 19:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 19;
            return 32;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 32:
         jjmatchedKind = 1;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x18L);
      case 33:
         return jjMoveStringLiteralDfa1_0(0x400L, 0x0L);
      case 38:
         return jjStopAtPos(0, 7);
      case 40:
         return jjStopAtPos(0, 65);
      case 41:
         return jjStopAtPos(0, 66);
      case 42:
         jjmatchedKind = 18;
         return jjMoveStringLiteralDfa1_0(0x80000L, 0x0L);
      case 43:
         return jjStopAtPos(0, 16);
      case 44:
         return jjStopAtPos(0, 61);
      case 45:
         return jjStopAtPos(0, 17);
      case 47:
         return jjStopAtPos(0, 20);
      case 58:
         return jjStopAtPos(0, 63);
      case 59:
         return jjStopAtPos(0, 58);
      case 60:
         jjmatchedKind = 12;
         return jjMoveStringLiteralDfa1_0(0x2000L, 0x0L);
      case 61:
         return jjMoveStringLiteralDfa1_0(0x800L, 0x0L);
      case 62:
         jjmatchedKind = 14;
         return jjMoveStringLiteralDfa1_0(0x8000L, 0x0L);
      case 64:
         return jjStopAtPos(0, 59);
      case 91:
         return jjStopAtPos(0, 60);
      case 93:
         return jjStopAtPos(0, 62);
      case 95:
         return jjStopAtPos(0, 64);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x10020000000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x55200000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000L);
      case 104:
         return jjMoveStringLiteralDfa1_0(0x5d80000000000L, 0x8000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0xa24ff00000000L, 0x400L);
      case 106:
         return jjMoveStringLiteralDfa1_0(0x80000000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x20000000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x400000L, 0x40L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x200L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x50000000000000L, 0x1800L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x2000000a800000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x180L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000L);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x100L, 0x0L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 42:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(1, 19);
         break;
      case 61:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(1, 10);
         else if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(1, 11);
         else if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(1, 13);
         else if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(1, 15);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x5d80000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x2005f800000L, active1, 0x4040L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L, active1, 0x8000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000020000000L, active1, 0x2000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0xff00000000L, active1, 0x400L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x60000080400200L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1020L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0xa240000000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x980L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x200L);
      case 124:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(1, 8);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x10020040000000L, active1, 0x6010L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x900L);
      case 100:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 22, 32);
         break;
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x8020L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0xff00000000L, active1, 0L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0xa800000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L, active1, 0x1008L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000020000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x40L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x80L);
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x15000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x45d80000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 32);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x600L);
      case 118:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(2, 21, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000L, active1, 0L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x1100000000000L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000L, active1, 0L);
      case 86:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000015000000L, active1, 0x680L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000a800000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L, active1, 0x800L);
      case 109:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(3, 57, 32);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x40080000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x220ff20000000L, active1, 0x100L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x8018L);
      case 116:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 57, 32);
         break;
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L, active1, 0x1000L);
      case 121:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000L, active1, 0x9000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x400020000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x8020000000000L, active1, 0x40L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x15000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x850000000000L, active1, 0x800L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x200040000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x5000000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x200ff00000000L, active1, 0x780L);
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000a800000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000000L, active1, 0x38L);
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 82:
         return jjMoveStringLiteralDfa6_0(active0, 0x10020000000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000020000000L, active1, 0L);
      case 99:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(5, 57, 32);
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100L);
      case 101:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 45, 32);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000015000000L, active1, 0x10L);
      case 109:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 49, 32);
         return jjMoveStringLiteralDfa6_0(active0, 0xff00000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0xc000080000000L, active1, 0x600L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L, active1, 0x20L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000L, active1, 0L);
      case 114:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(5, 57, 32);
         return jjMoveStringLiteralDfa6_0(active0, 0x110000000000L, active1, 0x8000L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x1800000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 42, 32);
         return jjMoveStringLiteralDfa6_0(active0, 0xa800000L, active1, 0x1000L);
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x8L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L, active1, 0L);
      case 77:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000L, active1, 0L);
      case 81:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000000L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa7_0(active0, 0x1800000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x608L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000L, active1, 0x8010L);
      case 101:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 43, 32);
         else if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(6, 57, 32);
         return jjMoveStringLiteralDfa7_0(active0, 0x51000a800000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x1800080000000L, active1, 0x180L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x50020000000000L, active1, 0L);
      case 114:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(6, 57, 32);
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa7_0(active0, 0x15000000L, active1, 0L);
      case 116:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 51, 32);
         return jjMoveStringLiteralDfa7_0(active0, 0x4000020000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 82:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x2040000000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000220000000L, active1, 0L);
      case 103:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000L, active1, 0L);
      case 104:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x8000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x10L);
      case 108:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(7, 57, 32);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(7, 57, 32);
         return jjMoveStringLiteralDfa8_0(active0, 0x10020000000000L, active1, 0x8L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x40101800000000L, active1, 0x100L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0xc000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0xa800000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000000L, active1, 0x80L);
      case 116:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(7, 31, 32);
         return jjMoveStringLiteralDfa8_0(active0, 0x1000015000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(8, 67);
         break;
      case 67:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa9_0(active0, 0x22000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000L, active1, 0x100L);
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 41, 32);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 52, 32);
         return jjMoveStringLiteralDfa9_0(active0, 0x115000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x21801800000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000000L, active1, 0x80L);
      case 112:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x10L);
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0xa000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 44, 32);
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000L, active1, 0L);
      case 121:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(8, 57, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x40000000000000L, active1, 0x10L);
      case 98:
         return jjMoveStringLiteralDfa10_0(active0, 0x200000000L, active1, 0L);
      case 101:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 38, 32);
         return jjMoveStringLiteralDfa10_0(active0, 0x40000000L, active1, 0L);
      case 103:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x400000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x810000000000L, active1, 0L);
      case 109:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 39, 32);
         break;
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000500800000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x100002a000000L, active1, 0L);
      case 114:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(9, 57, 32);
         return jjMoveStringLiteralDfa10_0(active0, 0x15000000L, active1, 0L);
      case 116:
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 9;
         }
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 50, 32);
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000L, active1, 0x100L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1);
      return 10;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa11_0(active0, 0x1044000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000000000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 40, 32);
         else if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(10, 57, 32);
         return jjMoveStringLiteralDfa11_0(active0, 0x2200000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000800000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0x22000000L, active1, 0L);
      case 110:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 48, 32);
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x10L);
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000008000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa11_0(active0, 0x500000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1);
      return 11;
   }
   switch(curChar)
   {
      case 82:
         return jjMoveStringLiteralDfa12_0(active0, 0x100000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(11, 25, 32);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(11, 29, 32);
         break;
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x400400000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0x20000000000000L, active1, 0L);
      case 109:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(11, 27, 32);
         break;
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0x1054000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000000L, active1, 0L);
      case 116:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(11, 23, 32);
         return jjMoveStringLiteralDfa12_0(active0, 0x802000000000L, active1, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(10, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, active1);
      return 12;
   }
   switch(curChar)
   {
      case 32:
         if ((active1 & 0x10L) != 0L)
            return jjStopAtPos(12, 68);
         break;
      case 78:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x60000001000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa13_0(active0, 0x401044000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa13_0(active0, 0x100000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa13_0(active0, 0x10000000L, active1, 0L);
      case 115:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(12, 33, 32);
         break;
      case 116:
         return jjMoveStringLiteralDfa13_0(active0, 0x400000000L, active1, 0L);
      case 121:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 47, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0, active1);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(11, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(13, 26, 32);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(13, 30, 32);
         return jjMoveStringLiteralDfa14_0(active0, 0x1000000000L);
      case 105:
         return jjMoveStringLiteralDfa14_0(active0, 0x400000000000L);
      case 108:
         return jjMoveStringLiteralDfa14_0(active0, 0x100000000L);
      case 109:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(13, 28, 32);
         break;
      case 110:
         return jjMoveStringLiteralDfa14_0(active0, 0x40000000000000L);
      case 111:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000000000L);
      case 116:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(13, 24, 32);
         return jjMoveStringLiteralDfa14_0(active0, 0x20000000000000L);
      case 121:
         return jjMoveStringLiteralDfa14_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 77:
         return jjMoveStringLiteralDfa15_0(active0, 0x400000000L);
      case 97:
         return jjMoveStringLiteralDfa15_0(active0, 0x40000000000000L);
      case 101:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(14, 32, 32);
         break;
      case 114:
         return jjMoveStringLiteralDfa15_0(active0, 0x2000000000L);
      case 115:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(14, 36, 32);
         break;
      case 116:
         return jjMoveStringLiteralDfa15_0(active0, 0x400000000000L);
      case 121:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(14, 53, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa16_0(active0, 0x400000000L);
      case 108:
         return jjMoveStringLiteralDfa16_0(active0, 0x40000000000000L);
      case 109:
         return jjMoveStringLiteralDfa16_0(active0, 0x2000000000L);
      case 121:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(15, 46, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(14, active0, 0L);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0, 0L);
      return 16;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa17_0(active0, 0x40000000000000L);
      case 109:
         return jjMoveStringLiteralDfa17_0(active0, 0x400000000L);
      case 115:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(16, 37, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, active0, 0L);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0, 0L);
      return 17;
   }
   switch(curChar)
   {
      case 98:
         return jjMoveStringLiteralDfa18_0(active0, 0x400000000L);
      case 116:
         return jjMoveStringLiteralDfa18_0(active0, 0x40000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0, 0L);
}
private int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0, 0L);
      return 18;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa19_0(active0, 0x400000000L);
      case 121:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(18, 54, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(17, active0, 0L);
}
private int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0, 0L);
      return 19;
   }
   switch(curChar)
   {
      case 114:
         return jjMoveStringLiteralDfa20_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(18, active0, 0L);
}
private int jjMoveStringLiteralDfa20_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(18, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0, 0L);
      return 20;
   }
   switch(curChar)
   {
      case 115:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(20, 34, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(19, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 33;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 28:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAdd(28);
                  break;
               case 23:
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjstateSet[jjnewStateCnt++] = 30;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  else if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     jjCheckNAdd(30);
                  }
                  if ((0x1804000000000L & l) != 0L)
                  {
                     if (kind > 5)
                        kind = 5;
                  }
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 8;
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 23:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 25:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 8:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 19:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 12:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 21:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 14:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 24:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 26:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 13:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 22:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 15:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 20:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(32);
                  }
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 1:
                  if (curChar == 101 && kind > 6)
                     kind = 6;
                  break;
               case 2:
               case 10:
               case 17:
                  if (curChar == 109)
                     jjCheckNAdd(1);
                  break;
               case 3:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 11:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 16:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 27:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 29:
                  if ((0x7fffffeL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAdd(30);
                  break;
               case 30:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAdd(30);
                  break;
               case 31:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               case 32:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(32);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 33 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\46", "\174\174", "\156\157\164", 
"\41\75", "\75\75", "\74", "\74\75", "\76", "\76\75", "\53", "\55", "\52", "\52\52", 
"\57", "\144\151\166", "\155\157\144", 
"\162\145\147\151\163\164\145\162\125\156\151\164", "\144\145\162\145\147\151\163\164\145\162\125\156\151\164", 
"\162\145\147\151\163\164\145\162\122\157\154\145", "\144\145\162\145\147\151\163\164\145\162\122\157\154\145", 
"\162\145\147\151\163\164\145\162\116\157\162\155", "\144\145\162\145\147\151\163\164\145\162\116\157\162\155", 
"\141\154\154\157\143\141\164\145\122\157\154\145", "\144\145\141\154\154\157\143\141\164\145\122\157\154\145", 
"\152\157\151\156\125\156\151\164", "\151\156\146\157\162\155\101\147\145\156\164\122\157\154\145", 
"\151\156\146\157\162\155\115\145\155\142\145\162\163", 
"\151\156\146\157\162\155\121\165\141\156\164\151\164\171\115\145\155\142\145\162\163", "\151\156\146\157\162\155\125\156\151\164", 
"\151\156\146\157\162\155\125\156\151\164\122\157\154\145\163", "\151\156\146\157\162\155\124\141\162\147\145\164\116\157\162\155\163", 
"\151\156\146\157\162\155\122\157\154\145", "\151\156\146\157\162\155\116\157\162\155", 
"\141\143\161\165\151\162\145\122\157\154\145", "\154\145\141\166\145\122\157\154\145", "\151\163\125\156\151\164", 
"\150\141\163\124\171\160\145", "\150\141\163\120\141\162\145\156\164", "\151\163\122\157\154\145", 
"\150\141\163\101\143\143\145\163\163\151\142\151\154\151\164\171", "\150\141\163\126\151\163\151\142\151\154\151\164\171", 
"\150\141\163\120\157\163\151\164\151\157\156", "\151\163\116\157\162\155", "\150\141\163\103\157\156\164\145\156\164", 
"\151\163\101\147\145\156\164", "\160\154\141\171\163\122\157\154\145", 
"\162\157\154\145\103\141\162\144\151\156\141\154\151\164\171", 
"\160\157\163\151\164\151\157\156\103\141\162\144\151\156\141\154\151\164\171", null, null, null, "\73", "\100", "\133", "\54", "\135", "\72", "\137", "\50", 
"\51", "\40\166\151\162\164\165\141\154\40", 
"\40\160\141\162\164\151\143\151\160\141\156\164\40", "\143\162\145\141\164\157\162", "\155\145\155\142\145\162", 
"\163\165\160\145\162\166\151\163\157\162", "\163\165\142\157\162\144\151\156\141\164\145", 
"\145\170\164\145\162\156\141\154", "\151\156\164\145\162\156\141\154", "\160\165\142\154\151\143", 
"\160\162\151\166\141\164\145", "\146\154\141\164", "\164\145\141\155", 
"\150\151\145\162\141\162\143\150\171", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffffe1L, 0xffffL, 
};
static final long[] jjtoSkip = {
   0x1eL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[33];
private final int[] jjstateSet = new int[66];
protected char curChar;
/** Constructor. */
public NormsTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public NormsTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 33; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
