/* Generated By:JavaCC: Do not edit this line. NormParserConstants.java */
package es.upv.dsic.gti_ia.norms;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NormParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int deontic = 5;
  /** RegularExpression Id. */
  int agentName = 6;
  /** RegularExpression Id. */
  int roleName = 7;
  /** RegularExpression Id. */
  int positionName = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int NOTEQUAL = 12;
  /** RegularExpression Id. */
  int EQUAL = 13;
  /** RegularExpression Id. */
  int LESS = 14;
  /** RegularExpression Id. */
  int LESSOREQUAL = 15;
  /** RegularExpression Id. */
  int HIGHER = 16;
  /** RegularExpression Id. */
  int HIGHEROREQUAL = 17;
  /** RegularExpression Id. */
  int SUM = 18;
  /** RegularExpression Id. */
  int SUBTRACTION = 19;
  /** RegularExpression Id. */
  int MULTIPLICATION = 20;
  /** RegularExpression Id. */
  int POWER = 21;
  /** RegularExpression Id. */
  int DIVISION = 22;
  /** RegularExpression Id. */
  int INTDIVISION = 23;
  /** RegularExpression Id. */
  int MODULE = 24;
  /** RegularExpression Id. */
  int registerUnit = 25;
  /** RegularExpression Id. */
  int deregisterUnit = 26;
  /** RegularExpression Id. */
  int registerRole = 27;
  /** RegularExpression Id. */
  int deregisterRole = 28;
  /** RegularExpression Id. */
  int registerNorm = 29;
  /** RegularExpression Id. */
  int deregisterNorm = 30;
  /** RegularExpression Id. */
  int allocateRole = 31;
  /** RegularExpression Id. */
  int deallocateRole = 32;
  /** RegularExpression Id. */
  int joinUnit = 33;
  /** RegularExpression Id. */
  int informAgentRole = 34;
  /** RegularExpression Id. */
  int informMembers = 35;
  /** RegularExpression Id. */
  int informQuantityMembers = 36;
  /** RegularExpression Id. */
  int informUnit = 37;
  /** RegularExpression Id. */
  int informUnitRoles = 38;
  /** RegularExpression Id. */
  int informTargetNorms = 39;
  /** RegularExpression Id. */
  int informRole = 40;
  /** RegularExpression Id. */
  int informNorm = 41;
  /** RegularExpression Id. */
  int acquireRole = 42;
  /** RegularExpression Id. */
  int leaveRole = 43;
  /** RegularExpression Id. */
  int OMSPositions = 44;
  /** RegularExpression Id. */
  int OMSaccessibility = 45;
  /** RegularExpression Id. */
  int OMSVisibility = 46;
  /** RegularExpression Id. */
  int OMSUnitTypes = 47;
  /** RegularExpression Id. */
  int isUnit = 48;
  /** RegularExpression Id. */
  int hasType = 49;
  /** RegularExpression Id. */
  int hasParent = 50;
  /** RegularExpression Id. */
  int isRole = 51;
  /** RegularExpression Id. */
  int hasAccessibility = 52;
  /** RegularExpression Id. */
  int hasVisibility = 53;
  /** RegularExpression Id. */
  int hasPosition = 54;
  /** RegularExpression Id. */
  int isNorm = 55;
  /** RegularExpression Id. */
  int hasDeontic = 56;
  /** RegularExpression Id. */
  int hasTarget = 57;
  /** RegularExpression Id. */
  int hasAction = 58;
  /** RegularExpression Id. */
  int isAgent = 59;
  /** RegularExpression Id. */
  int playsRole = 60;
  /** RegularExpression Id. */
  int roleCardinality = 61;
  /** RegularExpression Id. */
  int positionCardinality = 62;
  /** RegularExpression Id. */
  int numericConstant = 63;
  /** RegularExpression Id. */
  int variable = 64;
  /** RegularExpression Id. */
  int stringConstant = 65;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<deontic>",
    "\"agentName\"",
    "\"roleName\"",
    "\"positionName\"",
    "\"&\"",
    "\"|\"",
    "\"not\"",
    "\"\\\\==\"",
    "\"==\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"**\"",
    "\"/\"",
    "\"div\"",
    "\"mod\"",
    "\"registerUnit\"",
    "\"deregisterUnit\"",
    "\"registerRole\"",
    "\"deregisterRole\"",
    "\"registerNorm\"",
    "\"deregisterNorm\"",
    "\"allocateRole\"",
    "\"deallocateRole\"",
    "\"joinUnit\"",
    "\"informAgentRole\"",
    "\"informMembers\"",
    "\"informQuantityMembers\"",
    "\"informUnit\"",
    "\"informUnitRoles\"",
    "\"informTargetNorms\"",
    "\"informRole\"",
    "\"informNorm\"",
    "\"acquireRole\"",
    "\"leaveRole\"",
    "<OMSPositions>",
    "<OMSaccessibility>",
    "<OMSVisibility>",
    "<OMSUnitTypes>",
    "\"isUnit\"",
    "\"hasType\"",
    "\"hasParent\"",
    "\"isRole\"",
    "\"hasAccessibility\"",
    "\"hasVisibility\"",
    "\"hasPosition\"",
    "\"isNorm\"",
    "\"hasDeontic\"",
    "\"hasTarget\"",
    "\"hasAction\"",
    "\"isAgent\"",
    "\"playsRole\"",
    "\"roleCardinality\"",
    "\"positionCardinality\"",
    "<numericConstant>",
    "<variable>",
    "<stringConstant>",
    "\"@\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\":\"",
    "\"_\"",
    "\"(\"",
    "\")\"",
  };

}
